"""empty message

Revision ID: 255c777e8ef3
Revises: b79f987d2c7c
Create Date: 2026-01-28 20:35:49.442813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255c777e8ef3'
down_revision = 'b79f987d2c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=120), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user_posts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('post_comments',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], )
    )
    op.create_table('post_media',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('media', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media'], ['media.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], )
    )
    op.create_table('user_comments',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('follower')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'])

    op.create_table('follower',
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_from_id', name='follower_pkey'),
    sa.UniqueConstraint('user_to_id', name='follower_user_to_id_key')
    )
    op.drop_table('user_comments')
    op.drop_table('post_media')
    op.drop_table('post_comments')
    op.drop_table('user_posts')
    op.drop_table('media')
    op.drop_table('comment')
    op.drop_table('post')
    # ### end Alembic commands ###
