"""empty message

Revision ID: 3344b30115f2
Revises: ac1d1c6ce5f4
Create Date: 2026-01-30 19:04:17.413236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3344b30115f2'
down_revision = 'ac1d1c6ce5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('same_type_posts',
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['mediatype.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('same_type_posts')
    # ### end Alembic commands ###
