"""empty message

Revision ID: b79f987d2c7c
Revises: da321f703be2
Create Date: 2026-01-28 18:38:12.966585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79f987d2c7c'
down_revision = 'da321f703be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_from_id'),
    sa.UniqueConstraint('user_from_id'),
    sa.UniqueConstraint('user_to_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
