"""empty message

Revision ID: d25b635abbdf
Revises: 3344b30115f2
Create Date: 2026-02-10 23:42:38.895850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25b635abbdf'
down_revision = '3344b30115f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_posts')
    op.drop_table('same_type_posts')
    op.drop_table('user_followers')
    op.drop_table('user_comments')
    op.drop_table('post_comments')
    op.drop_table('post_media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_media',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media'], ['media.id'], name='post_media_media_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_media_post_id_fkey')
    )
    op.create_table('post_comments',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment'], ['comment.id'], name='post_comments_comment_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_comments_post_id_fkey')
    )
    op.create_table('user_comments',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='user_comments_comment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_comments_user_id_fkey')
    )
    op.create_table('user_followers',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_followers_user_id_fkey')
    )
    op.create_table('same_type_posts',
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='same_type_posts_media_id_fkey'),
    sa.ForeignKeyConstraint(['type_id'], ['mediatype.id'], name='same_type_posts_type_id_fkey')
    )
    op.create_table('user_posts',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='user_posts_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_posts_user_id_fkey')
    )
    # ### end Alembic commands ###
