"""empty message

Revision ID: d82d852968bd
Revises: d25b635abbdf
Create Date: 2026-02-10 23:46:50.184131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82d852968bd'
down_revision = 'd25b635abbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follow', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_follows_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follow'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_follows_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('follow')
        batch_op.drop_column('follower')

    # ### end Alembic commands ###
