"""empty message

Revision ID: d9d90fcb79cd
Revises: d82d852968bd
Create Date: 2026-02-13 03:44:12.794297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d90fcb79cd'
down_revision = 'd82d852968bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=120), nullable=False))
        batch_op.drop_column('latname')

    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.alter_column('follower',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('follow',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.alter_column('follow',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('follower',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('lastname')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
